jobs:
 - name: test
   plan:
      - get: repo
      - task: test
        config:
          platform: linux
          image_resource: 
            type: registry-image
            source: { repository: node, tag: "8" }
          inputs: 
            - name: repo
          run:
            path: /bin/bash
            args:
              - -c
              - set -e
                cd repo
                npm run tests

resources:
  - name: repo
    type: git
    icon: github-circle
    source:
      uri: https://github.com/CranberryYam/conc.git
      branch: master